### ISSUE TITLE
main.amx

### ISSUE THREAD

**Issue by WoufWouf35** [Larceny-/samp-missions#1]
Hey broo, it's been a long since your update. But, i need the main.amx so this gamemode can runs on my hosting server. Thanks, broo. Regard

**Comment by Zaltoman** [comment]
Hey man, if you're still looking for this, you can compile the gamemode yourself using pawno.

**Comment by Maxiusha** [comment]
How to download all files?pls help

**Comment by ElidaViana10** [comment]
> Hey broo, it's been a long since your update. But, i need the main.amx so this gamemode can runs on my hosting server. Thanks, broo. Regard

hello, I don't know if you managed to test it but I wanted to know if the gm has npcs or all the missions in the game

**Comment by wuzi** [comment]
> Hey broo, it's been a long since your update. But, i need the main.amx so this gamemode can runs on my hosting server. Thanks, broo. Regard

hey, you can compile from the files in the repository



> How to download all files?pls help

you can clone with git or download zip here
https://github.com/wuzi/samp-missions/archive/refs/heads/master.zip

> hello, I don't know if you managed to test it but I wanted to know if the gm has npcs or all the missions in the game

hey, doesn't have all npc and missions, only the intro until groove street and the burglar mission
